package QuizGame;

import java.util.HashMap;

public class GenerateData {
    private static final String[][] files = {
            {"Afghanistan","Kaboul"},
            {"Afrique du Sud","Pretoria"},
            {"Algérie","Alger"},
            {"Allemagne","Berlin"},
            {"Arabie Saoudite","Riyad"},
            {"Australie","Canberra"},
            {"Autriche","Vienne"},
            {"Bangladesh","Dacca"},
            {"Belgique","Bruxelles"},
            {"Biélorussie","Minsk"},
            {"Bolivie","Sucre"},
            {"Brésil","Brasília"},
            {"Canada","Ottawa"},
            {"Chili","Santiago"},
            {"Chine","Pékin"},
            {"Colombie","Bogotá"},
            {"Corée du Sud","Séoul"},
            {"Croatie","Zagreb"},
            {"Cuba","La Havane"},
            {"Danemark","Copenhague"},
            {"Égypte","Le Caire"},
            {"Espagne","Madrid"},
            {"Finlande","Helsinki"},
            {"France","Paris"},
            {"Ghana","Accra"},
            {"Grèce","Athènes"},
            {"Guatemala","Guatemala"},
            {"Honduras","Tegucigalpa"},
            {"Hongrie","Budapest"},
            {"Inde","New Delhi"},
            {"Indonésie","Jakarta"},
            {"Irak","Bagdad"},
            {"Iran","Téhéran"},
            {"Irlande","Dublin"},
            {"Italie","Rome"},
            {"Jamaïque","Kingston"},
            {"Japon","Tokyo"},
            {"Jordanie","Amman"},
            {"Kazakhstan","Astana"},
            {"Kenya","Nairobi"},
            {"Liban","Beyrouth"},
            {"Libye","Tripoli"},
            {"Liechtenstein","Vaduz"},
            {"Luxembourg","Luxembourg"},
            {"Madagascar","Antananarivo"},
            {"Malaisie","Kuala Lumpur"},
            {"Maroc","Rabat"},
            {"Mexique","Mexico"},
            {"Monaco","Monaco"},
            {"Myanmar","Naypyidaw"},
            {"Nigéria","Abuja"},
            {"Norvège","Oslo"},
            {"Nouvelle-Zélande","Wellington"},
            {"Ouganda","Kampala"},
            {"Ouzbékistan","Tachkent"},
            {"Pakistan","Islamabad"},
            {"Panama","Panama"},
            {"Paraguay","Asuncion"},
            {"Pays-Bas","Amsterdam"},
            {"Pérou","Lima"},
            {"Philippines","Manille"},
            {"Pologne","Varsovie"},
            {"Portugal","Lisbonne"},
            {"Qatar","Doha"},
            {"Roumanie","Bucarest"},
            {"Royaume-Uni","Londres"},
            {"Russie","Moscou"},
            {"Sénégal","Dakar"},
            {"Serbie","Belgrade"},
            {"Singapour","Singapour"},
            {"Slovaquie","Bratislava"},
            {"Slovénie","Ljubljana"},
            {"Suède","Stockholm"},
            {"Suisse","Berne"},
            {"Syrie","Damas"},
            {"Tanzanie","Dodoma"},
            {"Thaïlande","Bangkok"},
            {"Tchéquie","Prague"},
            {"Tunisie","Tunis"},
            {"Turquie","Ankara"},
            {"Ukraine","Kyiv"},
            {"Uruguay","Montevideo"},
            {"Venezuela","Caracas"},
            {"Vietnam","Hanoï"},
            {"Zambie","Lusaka"},
            {"Zimbabwe","Harare"}
    };
    private static final HashMap<String, String> data = new HashMap<>();

    public static HashMap<String, String> getData(){
        for (int i = 0; i< files.length; i++) data.put(files[i][0], files[i][1]);
        return data;
    }
}
